### ISSUE TITLE
pr-diff-checker : add exclude parameter to skip validation on non documentation files

### ISSUE THREAD

**Issue by uguy** [bonitasoft/actions#112]
A PR is blocked because the pr-diff-checker does not allow to have a link to bonitasoft documentation in the repository README.adoc file.

See : https://github.com/bonitasoft/bonita-central-doc/pull/18

**Comment by tbouffard** [comment]
Alternatively, we could let specify a glob for the path to consider. That way, we could only check the Antora pages/resources and not other files in the repository.
Notice that we plan to create a shared action to centralize the configuration of pr-diff-checker used in the context of the bonita documentation.

cc @benjaminParisel

**Comment by tbouffard** [comment]
`pr-diff-checker` is going to be deprecated/removed as it is not use in repositories that store the documentation content.
So closing this issue.
